extends Sprite2D
@onready var abillity_card_choose_menu: Control = $GUI/abillityCardChooseMenu

var float_speed = 2.0
var float_height = 1.4
var start_y = 0.0
var time_passed = 0.0 

func _ready():
	start_y = global_position.y  # Store initial position

func _process(delta):
	time_passed += delta * float_speed  # Increase time
	global_position.y = start_y + sin(time_passed) * float_height  # Apply sine wave

func _on_area_2d_body_entered(body: Node2D) -> void:
	print("Body entered the orb")
	if abillity_card_choose_menu:
		abillity_card_choose_menu.visible = true
	queue_free()
	
