extends Control
@onready var pause_menu: Control = $"."
@onready var options_menu: Control = $"Options Menu"

func _ready() -> void:
	options_menu.visible = false	
	
func _on_resume_pressed() -> void:
	pause_menu.visible = false
	get_tree().paused = false

func _on_options_pressed() -> void:
	get_tree().paused = true
	options_menu.visible = true
	pause_menu.visible = true
	options_menu.update_ui()

func _on_exit_to_levels_map_pressed() -> void:
	get_tree().paused = false
	get_tree().call_deferred("change_scene_to_file", "res://scenes/world_map.tscn")

func _on_exit_to_main_menu_pressed() -> void:
	get_tree().paused = false
	get_tree().call_deferred("change_scene_to_file", "res://scenes/main_menu.tscn")
